### ISSUE TITLE
dockerで環境構築

### ISSUE THREAD

**Issue by tomishima2904** [tomishima2904/es_manager#1]
ルートディレクトリに`docker`ディレクトリを作成し、その中に以下の3つのディレクトリを作成する。
- `app`: Spring BootのDockerfileを持つ
- `front`: ReactのDockerfileを持つ
- `db`: データベースのDockerfileを持つ（データベースの種類は何でも良い）

そして、`docker-compose.yml`はルートディレクトリに作成する。

**Comment by mctomoney** [comment]
とりあえず雛形だけのdocker-compose.ymlをルートディレクトリに配置した（はず）ので確認してみてくれ

**Comment by tomishima2904** [comment]
作業内容をコミットしただけではこちら側では見れないので、作業ブランチをpushしてくれい
`git push origin <作業ブランチ名>`で行けるはず

**Comment by mctomoney** [comment]
なるほど。作業ブランチとか意識せずやってしまったかもしれない
デフォルトで作業ブランチは何て名前？

**Comment by tomishima2904** [comment]
ちなみにgit系の操作は[source tree](https://www.sourcetreeapp.com/)ていうアプリが便利だからインストールするのを推奨

**Comment by tomishima2904** [comment]
> mysqlのイメージをdockerhubから引っ張ってきたんだがこれをどうすればいいんや

引っ張ってきたイメージに対してアレンジ（環境変数の設定だったり、文字コードの設定）をするには`db/Dockerfile`にその内容を記述するといいぞ。ただ、mysqlのイメージに関して言えばそこまでアレンジする必要性はないぽい(？)

**Comment by mctomoney** [comment]
> 

今おそらく別の問題が出てて、
<img width="832" alt="スクリーンショット 2023-03-30 13 42 12" src="https://user-images.githubusercontent.com/129293018/228731484-ac62c94a-d608-4453-aa86-43a1f70b8ec4.png">
認証がだめみたい

**Comment by mctomoney** [comment]
> 引っ張ってきたイメージに対してアレンジ（環境変数の設定だったり、文字コードの設定）をするにはdb/Dockerfileにその内容を記述するといいぞ。
俺の理解だと、containerをbuildするのに必要なのがイメージで、イメージの作成に必要なのがDockerfileだと思ってた。dockerhubからイメージを直接pullしてきたからてっきりDockerfileはいらんのかと

**Comment by tomishima2904** [comment]
あーGithubの認証の問題俺も前出たなー。解決方法忘れたけどそのエラー文ググればすぐ出てくると思う笑

**Comment by tomishima2904** [comment]
> 俺の理解だと、containerをbuildするのに必要なのがイメージで、イメージの作成に必要なのがDockerfileだと思ってた。dockerhubからイメージを直接pullしてきたからてっきりDockerfileはいらんのかと

dockerhubで引っ張ってきたイメージだけで理想的な環境が作れることはあまりないので、Dockerfile上でdockerhubからプルしてきたイメージに対して、自分なりにレイヤーを重ねて（理想的なイメージを作るために環境変数だったりモジュールのインポート）、理想的なイメージを作成するという感じ

**Comment by tomishima2904** [comment]
そこで、Dockerfileの1行目には`FROM <dockerhubから引っ張ってくるイメージ>`を記入して、その下に俺らオリジナルの環境変数の設定文（`ENV 〜`）だったり、モジュールのインポート文（`RUN apt install 〜`）といったレイヤーを重ねていく感じ。

**Comment by mctomoney** [comment]
> あーGithubの認証の問題俺も前出たなー。解決方法忘れたけどそのエラー文ググればすぐ出てくると思う笑

多分反映されてると思う。見れる？

**Comment by mctomoney** [comment]
> そこで、Dockerfileの1行目には`FROM <dockerhubから引っ張ってくるイメージ>`を記入して、その下に俺らオリジナルの環境変数の設定文（`ENV 〜`）だったり、モジュールのインポート文（`RUN apt install 〜`）といったレイヤーを重ねていく感じ。
> 
> **Dockerfileの作成というのは、元のイメージを継承してさらに自分たちに適したイメージを作り上げる作業**

すごく理解したわ
MySQLの場合はその作業があまりいらないかもしれないということね（現時点で十分だから）

**Comment by tomishima2904** [comment]
>  MySQLの場合はその作業があまりいらないかもしれないということね（現時点で十分だから）

そゆことや

> 多分反映されてると思う。見れる？

反映されてるわ。でも`master`ブランチでのコミットになってるから、新しいブランチを作って作業してくれい

**Comment by tomishima2904** [comment]
使用するイメージは以下を使うといいぞ
- [app](https://hub.docker.com/_/gradle): `gradle:7.6.1-idk-alpine` 
- [front](https://nodejs.org/en): `node:18.15.0-alpine`
- [db](https://www.mysql.com/jp/support/supportedplatforms/workbench.html): `mysql:8`

**Comment by mctomoney** [comment]
> 反映されてるわ。でもmasterブランチでのコミットになってるから、新しいブランチを作って作業してくれい

昨日やった作業はもう諦めるしかないんんか（masterでほっとくしかないのか）

**Comment by tomishima2904** [comment]
昨日やった作業から新たなブランチを派生させるのだ。ちなみにmasterブランチは俺が昨日少しコミットとプッシュして変更してしまったので、その内容を自分のローカルに反映させるためにプルするといいぞ。

1. `git pull origin master` でリモートリポジトリの変更をローカルに反映
2. `git checkout -b develop` で`master`ブランチから`develop`ブランチを作成して、チェックアウト（ブランチの切り替え）
3.  `git checkout -b feature/1.0/docker`でさらに`develop`ブランチから` feature/1.0/docker`ブランチを作成して、チェックアウト
4. 自分の作業を行う（コミット）。コミットしたら即pushをするといい（俺が作業内容を確認できるため）。

**Comment by tomishima2904** [comment]
vscodeの拡張機能で`Git Graph`ってやつがあるからそれをインストールしたり、sourcetreeを使ったりするとブランチの状況が把握しやすいからおすすめ

**Comment by mctomoney** [comment]
> 昨日やった作業から新たなブランチを派生させるのだ。
この昨日やった作業から新たなブランチっていうのは普通にgit branch <新規ブランチ名>じゃだめなのか？

**Comment by tomishima2904** [comment]
まずはリモートの変更をローカルにしてからじゃないと、色々面倒なこと（コンフリクト）が起きる可能性があるので、とりあえずリポジトリを最新の状況にする（pull）。

そして、 `git branch <新規ブランチ名>`でオーケー。
ちなみに`git checkout -b <新規ブランチ名>`はブランチの作成とチェックアウトを同時に行うから便利
