### ISSUE TITLE
フロントとバックで分業

### ISSUE THREAD

**Issue by tomishima2904** [tomishima2904/es_manager#4]
#1 
ディレクトリ構成を以下のようにして、backendとfrontendをきっちり分けたほうが作業しやすそうだし、[一例](https://github.com/docker/awesome-compose/tree/master/react-java-mysql)を見たらこうなってるので、俺らもこれに倣おうと思う。
なので、既存のルートディレクトリにあるやつ（`.gitignore`と`docker-compose.yml`以外）を`backend`というディレクトリに階層を移して、`docker compose up`がちゃんとできるようにする。

`frontend`ディレクトリは追って作成する。
```
myapp/
├── backend/
│   ├── src/
│   │   ├── main/
│   │   │   ├── java/
│   │   │   │   └── com.example.myapp/
│   │   │   │       ├── controller/
│   │   │   │       ├── model/
│   │   │   │       ├── repository/
│   │   │   │       └── MyApplication.java
│   │   │   └── resources/
│   │   │       ├── application.properties
│   │   │       └── static/
│   │   └── test/
│   └── pom.xml
└── frontend/
    ├── public/
    │   ├── index.html
    │   └── favicon.ico
    ├── src/
    │   ├── components/
    │   ├── containers/
    │   ├── pages/
    │   ├── services/
    │   ├── styles/
    │   ├── App.js
    │   ├── index.js
    │   └── setupTests.js
    ├── package.json
    └── yarn.lock
```

**Comment by tomishima2904** [comment]
トライしてみてくれ。ディレクトリ移して、yamlのvolumesを少し書き換えるだけでできると思われる

**Comment by mctomoney** [comment]
一番上の例のディレクトリ構成を見る限り、backend内には.gitignoreとdocker-compose.yml以外のファイルが全てあるわけではないように見えるのだけど、単純に言葉通り.gitignoreとdocker-compose.yml以外全部をbackendに移動させれば良い？

あとvolumesは
`volumes: 
  - ./backend/:/app`
でいいのか？

**Comment by mctomoney** [comment]
上の例は俺らの例ではなく他の例の引用か？

**Comment by tomishima2904** [comment]
上の例のディレクトリ構成は俺らのじゃなくて一般的な例（チャットGPTの出力）だ
だからgitignoreとyaml以外を下の階層に移してもらって大丈夫

volumes も多分それで平気な気する

**Comment by tomishima2904** [comment]
それでdocker-compose buildと upやってみてうまくいけば成功。UPの方は1分くらいかかるかも。

あと.githubフォルダはルートディレクトリにおいておいてくれい

**Comment by mctomoney** [comment]
おけい

**Comment by tomishima2904** [comment]
全コンテナに共通する系のファイル（yamlとか.envとかGit系）はルートディレクトリに置いちゃってOK

**Comment by tomishima2904** [comment]
完璧だ

**Comment by mctomoney** [comment]
私springbootの勉強しますわ
