### ISSUE TITLE
docker compose で Reactのコンテナを作成

### ISSUE THREAD

**Issue by tomishima2904** [tomishima2904/es_manager#5]
#1 #4 以下の条件を満たすものとする
- ディレクトリの名前は`frontend`とし、Typescriptでプロジェクトを作成する。おそらく`create-react-app frontend (--template typescript)` こんな感じのコマンド
- イメージは `node:18.15.0-alpine`
- ポート番号は`3001`
- パッケージ管理ツールは`npm`**ではなく**`yarn`で行う

参考サイト: [dockerでReact環境を構築](https://zenn.dev/rihito/articles/96dfad8d4990f9)

**Comment by mctomoney** [comment]
一つ問題というか疑問点が
ymlのappコンテナの記述のところで、volumesを
`volumes:  ./backend/:/app`
にしてるせいで、コンテナ側のappディレクトリ配下にbackendディレクトリが展開されてvolumeされてるのだけどこれは問題ない？
俺的にはコンテナ側のappの配下にbackendとfrontendがあってそこからさらに下に作業ディレクトリがあるイメージだったから、appコンテナとfrontコンテナのvolumesの書き方をそれぞれ
`volumes:  ./backend:/app`　（⇦app）
`volumes:  ./frontend:/app`　（⇦front）
にしても大丈夫？

**Comment by tomishima2904** [comment]
> 一つ問題というか疑問点が ymlのappコンテナの記述のところで、volumesを `volumes: ./backend/:/app` にしてるせいで、コンテナ側のappディレクトリ配下にbackendディレクトリが展開されてvolumeされてるのだけどこれは問題ない？

これで問題ない。`app`コンテナの方にほしいのは実は、gradleでbuildするのに必要なファイル（`gradel.build`とか`src`ディレクトリ以下すなわち`backend`ディレクトリにあるもの）だけで十分だから。htmlとかcssとかはbuildに関係ないらしいんよね。



>  appコンテナとfrontコンテナのvolumesの書き方をそれぞれ `volumes: ./backend:/app`　（⇦app） `volumes: ./frontend:/app`　（⇦front） にしても大丈夫？

それで大丈夫だけど、一応`front`のコンテナの方は`volumes: ./frontend:/front`とかにしとこかな

**Comment by tomishima2904** [comment]
もし色々試してコミットが汚くなりそうなら、`feature/1.0/docker`ブランチから、さらに`feature/1.0/docker_front`的なブランチ作ってそこで作業してもええで。
そんで後で、`feature/1.0/docker_front`を`feature/1.0/docker`にマージする感じで

**Comment by mctomoney** [comment]
一応、feature/1.0/docker_frontのブランチでymlのアップデートをコミットプッシュしたけどあってる？

**Comment by mctomoney** [comment]
ちなみにdocker compose up frontしたらこんな感じでhappy hacking!は出るけどエラーで終わる
<img width="605" alt="スクリーンショット 2023-04-05 11 05 11" src="https://user-images.githubusercontent.com/129293018/229962398-eff2956b-261b-4369-833b-ba100c1ed6b0.png">

**Comment by tomishima2904** [comment]
> 一応、feature/1.0/docker_frontのブランチでymlのアップデートをコミットプッシュしたけどあってる？

ブランチのコミットとプッシュは大丈夫

**Comment by tomishima2904** [comment]
> ちなみにdocker compose up frontしたらこんな感じでhappy hacking!は出るけどエラーで終わる <img alt="スクリーンショット 2023-04-05 11 05 11" width="605" src="https://user-images.githubusercontent.com/129293018/229962398-eff2956b-261b-4369-833b-ba100c1ed6b0.png">

エラー文にもある通り、コンテナ内の`frontend`ディレクトリに移動して`yarn start`しなきゃダメなんよね。だから`yaml`の`command`のところを`command: sh -c "cd react-sample && yarn start"にすればええんやない？

**Comment by tomishima2904** [comment]
ほんで、まずはReactのプロジェクトを作らなあかんから、以下のコマンドをやる感じかも
```
docker compose run --rm front sh -c "yarn install -g create-react-app && create-react-app frontend (--template typescript
```

**Comment by tomishima2904** [comment]
んで↓

**Comment by mctomoney** [comment]
なんかインタラクティブモードみたいになるな
<img width="1068" alt="スクリーンショット 2023-04-05 11 13 37" src="https://user-images.githubusercontent.com/129293018/229963532-651dcb8d-412a-43f0-a0b7-ebecd5511cac.png">

**Comment by tomishima2904** [comment]
> なんかインタラクティブモードみたいになるな 

そしたら、ymlの`tty`消してみる？

**Comment by tomishima2904** [comment]
あと、`frontend`っていうディレクトリ生成されてる？ローカルに

**Comment by mctomoney** [comment]
ymlのtty消してもだめだったな
frontendは生成されてないかな

**Comment by tomishima2904** [comment]
あ、"閉じてないわ

**Comment by mctomoney** [comment]
"で閉じて、`yarn install -g create-react-app`を`yarn global add create-react-app`に直して実行したらfrontendの配下にfrontendってフォルダがローカルに作られてめちゃめちゃインストール進んでる

**Comment by tomishima2904** [comment]
`frontend`の下に`frontend`できちゃったか笑 まあそしたらそれは後で修正すればいいや笑
とりあえずうまくいってるぽいな

**Comment by mctomoney** [comment]
docker compose up frontもおそらく問題なく動作する
<img width="503" alt="スクリーンショット 2023-04-05 11 34 00" src="https://user-images.githubusercontent.com/129293018/229966519-b525ae04-54fa-424c-9fa0-7e9104c3e190.png">
ポート番号がちょっと怪しいけど

でちなみに

- ローカルにとんでもない量の変更が加えられてるのだけど、これは全てcommit & pushしても良い？
- 多分昔作ったfrontのDockerfileがずっとあって赤字で邪魔なんだけどこれも消していいよね？

**Comment by tomishima2904** [comment]
> docker compose up frontもおそらく問題なく動作する <img alt="スクリーンショット 2023-04-05 11 34 00" width="503" src="https://user-images.githubusercontent.com/129293018/229966519-b525ae04-54fa-424c-9fa0-7e9104c3e190.png"> ポート番号がちょっと怪しいけど

おそらく`yarn start`するときにポート番号を指定する必要があるのかもしれない。`app`のが必要だったように。


> * ローカルにとんでもない量の変更が加えられてるのだけど、これは全てcommit & pushしても良い？

だめだ笑  `frontend`の下におそらく`node_modules`っていうディレクトリがあるんかな？それを`.gitignore`にぶち込んでくれ。もしかしたら他にもgitで管理する必要がないディレクトリがあるかもしれん。


> * 多分昔作ったfrontのDockerfileがずっとあって赤字で邪魔なんだけどこれも消していいよね？

消してええで

**Comment by tomishima2904** [comment]
chatGPT曰く、下記のファイルorディレクトリをgitignoreしていいらしい
```
# Yarn auto-generated folders
node_modules/
.yarn/

# Yarn-generated files
yarn-error.log
yarn.lock
```

**Comment by mctomoney** [comment]
なんかねーgitignoreが既に作られてるのよね勝手に
<img width="303" alt="スクリーンショット 2023-04-05 11 44 55" src="https://user-images.githubusercontent.com/129293018/229967902-e63380e4-09a7-4015-a9bd-243f66e94a19.png">

**Comment by tomishima2904** [comment]
> なんかねーgitignoreが既に作られてるのよね勝手に <img alt="スクリーンショット 2023-04-05 11 44 55" width="303"

それルートディレクトリにあるやつ（俺らオリジナルのやつ）と別ものよね？
俺らオリジナルのやつに、chatGPTが提示したやつを書き足してくれ

**Comment by mctomoney** [comment]
sourcetree見てもcommitをする候補にnode_modulesだけ綺麗に抜けてる

**Comment by mctomoney** [comment]
<img width="391" alt="スクリーンショット 2023-04-05 11 49 30" src="https://user-images.githubusercontent.com/129293018/229968526-7d57c21f-2a9e-4e93-baaa-62e5d1b533f9.png">

**Comment by mctomoney** [comment]
とりあえず元々俺らが作ったgitignoreに追記した
勝手に作られた方のgitignoreも含めこれらをcommit push？

**Comment by tomishima2904** [comment]
それでオーケー
yamlとgitignoreはコミットを分けてくれると助かる

**Comment by mctomoney** [comment]
> それでオーケー yamlとgitignoreはコミットを分けてくれると助かる

これの意味は、
コミット①：yamlと（元々俺らが作った）gitignore
コミット②：その他
っていう意味か

それとも
コミット①：yamlのみ
コミット②：（元々俺らが作った）gitignore含めその他
っていう意味？

**Comment by tomishima2904** [comment]
3つに分けてくれると助かる. yamlと.gitignoreとそれ以外（frontend/）

**Comment by mctomoney** [comment]
完了した

**Comment by tomishima2904** [comment]
確認するわ
あと[vscodeの拡張機能](https://github.com/tomishima2904/es_manager/discussions/2#discussioncomment-5519697)入れといてくれい

**Comment by tomishima2904** [comment]
まだ確認途中やけどとりあえず、プルリク作成してみるか

[ここ](https://github.com/tomishima2904/es_manager/branches)にブランチが色々あるから、`feature/1.0/docker_react`ブランチで`New pull request`を選択してくれい。ほんで、マージ先は`feature/1.0/docker`にしてくれい。
プルリク送る時のコメントに、issue番号（ハッシュタグ数字 #1 ←こんな感じ）を盛り込んでおいてくれるお

**Comment by tomishima2904** [comment]
コンテナの立ち上げは完璧だ
あとはポート番号の問題だけ処理してえな
多分すぐできると思う
